vpn-policy-routing/luci-app-vpn-policy-routing: update with upstream

diff --git a/package/mypackages/vpn-policy-routing/files/vpn-policy-routing.init b/package/mypackages/vpn-policy-routing/files/vpn-policy-routing.init
--- a/package/mypackages/vpn-policy-routing/files/vpn-policy-routing.init
+++ b/package/mypackages/vpn-policy-routing/files/vpn-policy-routing.init
@@ -77,14 +77,15 @@ is_wg() { local proto; proto=$(uci -q get network."$1".proto); [ "${proto:0:9}" 
 is_tunnel() { is_l2tp "$1" || is_oc "$1" || is_ovpn "$1" || is_pptp "$1" || is_tor "$1" || is_wg "$1"; }
 is_wan() { [ -n "$wanIface4" ] && [ "$1" = "$wanIface4" ]; }
 is_wan6() { [ -n "$wanIface6" ] && [ "$1" = "$wanIface6" ]; }
-is_ignored_interface() { [ "${ignoredIfaces/$1}" != "$ignoredIfaces" ]; }
-is_supported_interface() { [ "${supportedIfaces/$1}" != "$supportedIfaces" ] || { ! is_ignored_interface "$1" && { is_wan "$1" || is_wan6 "$1" || is_tunnel "$1"; }; }; }
+is_ignored_interface() { string_match_word "$ignoredIfaces" "$1"; }
+is_supported_interface() { string_match_word "$supportedIfaces" "$1" || { ! is_ignored_interface "$1" && { is_wan "$1" || is_wan6 "$1" || is_tunnel "$1"; }; }; }
 is_ipv4() { expr "$1" : '[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*$' >/dev/null; }
 is_ipv6() { [ "${1//:}" != "$1" ]; }
 is_netmask() { local ip="${1%/*}"; [ "$ip" != "$1" ] && is_ipv4 "$ip"; }
 is_domain() { [ "${1//[a-zA-Z-]}" != "$1" ]; }
 is_phys_dev() { [ -n "$1" ] && [ -n "$ifconfigOutput" ] && echo "$ifconfigOutput" | grep -q "^${1}"; }
 is_turris() { /bin/ubus -S call system board | /bin/grep 'Turris' | /bin/grep -q '15.05'; }
+string_match_word() { echo "$1" | grep -q -w "$2"; }
 get_device_default_gw() { echo "$ip4RouteOutput" | grep -Eso -m1 "via ([0-9]{1,3}\\.){3}[0-9]{1,3} dev $1" | awk '{print $2}'; }
 get_device_default_gw6() { echo "$ip6RouteOutput" | grep -Eso -m1 "via ([0-9a-fA-F]{0,4}:){1,7}[0-9a-fA-F]{0,4}(/([0-9]){0,2}){0,2} dev $1" | awk '{print $2}' | awk -F "/" '{print $1}'; }
 get_device_gw() { echo "$ip4RouteOutput" | grep -Eso -m1 "^([0-9]{1,3}\\.){3}[0-9]{1,3} dev $1" | awk '{print $1}'; }
@@ -115,6 +116,7 @@ load_package_config() {
 	config_get icmpIface                'config' 'icmp_interface'
 	config_get ignoredIfaces            'config' 'ignored_interface'
 	config_get supportedIfaces          'config' 'supported_interface'
+
 	if [ -z "${verbosity##*[!0-9]*}" ] || [ "$verbosity" -lt 0 ] || [ "$verbosity" -gt 2 ]; then
 		verbosity=1
 	fi
@@ -169,16 +171,15 @@ is_enabled() {
 
 # shellcheck disable=SC2086
 ipt() {
-  local d failFlagIpv4=0 failFlagIpv6=1
-	d="${*//-A/-D}"; [ "$d" != "$*" ] && { iptables $d >/dev/null 2>&1; ip6tables $d >/dev/null 2>&1; }
-	d="${*//-I/-D}"; [ "$d" != "$*" ] && { iptables $d >/dev/null 2>&1; ip6tables $d >/dev/null 2>&1; }
-	d="${*//-N/-F}"; [ "$d" != "$*" ] && { iptables $d >/dev/null 2>&1; ip6tables $d >/dev/null 2>&1; }
-	d="${*//-N/-X}"; [ "$d" != "$*" ] && { iptables $d >/dev/null 2>&1; ip6tables $d >/dev/null 2>&1; }
+  local d failFlagIpv4=1 failFlagIpv6=1
+	for d in "${*//-A/-D}" "${*//-I/-D}" "${*//-N/-F}" "${*//-N/-X}"; do 
+		[ "$d" != "$*" ] && { iptables $d >/dev/null 2>&1; ip6tables $d >/dev/null 2>&1; }
+	done
 
-	d="$*"; iptables $d >/dev/null 2>&1 || failFlagIpv4=1
-	if [ "$ipv6Enabled" -ne 0 ]; then ip6tables $d >/dev/null 2>&1 && failFlagIpv6=0; fi
+	d="$*"; iptables $d >/dev/null 2>&1 && failFlagIpv4=0;
+	if [ "$ipv6Enabled" -gt 0 ]; then ip6tables $d >/dev/null 2>&1 && failFlagIpv6=0; fi
 
-	if [ "$failFlagIpv4" -eq 0 ] || [ "$failFlagIpv6" -eq 0 ]; then return 0; else return 1; fi
+	[ "$failFlagIpv4" -eq 0 ] || [ "$failFlagIpv6" -eq 0 ]
 }
 
 # shellcheck disable=SC2086
@@ -189,6 +190,7 @@ ips() {
 			[ "$dnsmasqEnabled" -eq 0 ] && return 1
 			[ "$ipv6Enabled" -ne 0 ] && ipset="${ipset},${ipset}6"
 			echo "ipset=/${param}/${ipset} # $comment" >> "$dnsmasqFile" || failFlagIpv4=1
+#			echo "ipset=/${param}/${ipset}" >> "$dnsmasqFile" || failFlagIpv4=1
 			if [ "$failFlagIpv4" -eq 0 ] && [ "$failFlagIpv6" -eq 0 ]; then return 0; else return 1; fi
 			;;
 		add)
@@ -242,6 +244,11 @@ insert_tor_policy() {
 insert_policy() {
 	local comment="$1" iface="$2" laddr="$3" lport="$4" raddr="$5" rport="$6" proto="${7:-tcp}" chain="${8:-PREROUTING}"
 	local mark=$(eval echo "\$mark_$iface")
+	if [ "$ipv6Enabled" -eq 0 ]; then
+		is_ipv6 "$laddr" && return 0
+		is_ipv6 "$raddr" && return 0
+	fi
+
 	[ -z "$mark" ] && processPolicyStatus="${processPolicyStatus}${_ERROR_}: unknown fw_mark for ${iface}!\\n"
 #	param="-t mangle -A VPR_${chain} -j MARK --set-xmark ${mark}/${fwMask}"
 	param="-t mangle -I VPR_${chain} 1 -j MARK --set-xmark ${mark}/${fwMask}"
@@ -250,7 +257,7 @@ insert_policy() {
 	[ -n "$raddr" ] && param="$param -d $raddr $appendRemotePolicy"
 	[ -n "$rport" ] && param="$param -p $proto -m multiport --dport ${rport//-/:}"
 	[ -n "$comment" ] && param="$param -m comment --comment $(echo "$comment" | tr '[\. ~`!@#$%^&*()\+/,<>?//;:]' '_')"
-	ipt "$param" || processPolicyStatus="${processPolicyStatus}${_ERROR_}: ipt $param\\n"
+	ipt "$param" || processPolicyStatus="${processPolicyStatus}${_ERROR_}: iptables $param\\n"
 	if [ "$outputChainEnabled" -ne 0 ] && [ "$chain" = "PREROUTING" ] && [ "$proto" = "tcp" ] && [ -z "$laddr" ]; then
 		if [ -n "$lport" ] || [ -n "$rport" ]; then
 			insert_policy "$1" "$2" "$3" "$4" "$5" "$6" "$proto" 'OUTPUT'
@@ -271,7 +278,7 @@ insert_phys_dev_policy() {
 	param="-t mangle -I VPR_${chain} 1 -j MARK --set-xmark ${mark}/${fwMask}"
 	[ -n "$phys_dev" ] && param="$param -i $phys_dev"
 	[ -n "$comment" ] && param="$param -m comment --comment $(echo "$comment" | tr '[\. ~`!@#$%^&*()\+/,<>?//;:]' '_')"
-	ipt "$param" || processPolicyStatus="${processPolicyStatus}${_ERROR_}: ipt $param\\n"
+	ipt "$param" || processPolicyStatus="${processPolicyStatus}${_ERROR_}: iptables $param\\n"
 	return 0
 }
 
@@ -393,8 +400,10 @@ table_create(){
 	if [ -n "$tid" ] && [ -n "$mark" ] && [ -n "$iface" ]; then
 		table_destroy "$tid" "$iface" "$mark"
 
-		if { [ -n "$gw4" ] && [ "$gw4" != "0.0.0.0" ]; } || [ "$strictMode" -ne 0 ]; then
-			if [ -z "$gw4" ] || [ "$gw4" = "0.0.0.0" ]; then
+#		if { [ -n "$gw4" ] && [ "$gw4" != "0.0.0.0" ]; } || [ "$strictMode" -ne 0 ]; then
+#			if [ -z "$gw4" ] || [ "$gw4" = "0.0.0.0" ]; then
+		if [ -n "$gw4" ] || [ "$strictMode" -ne 0 ]; then
+			if [ -z "$gw4" ]; then
 				ip -4 route add unreachable default table "$tid" >/dev/null 2>&1 || ipv4_error=1
 			else
 				ip -4 route add default via "$gw4" dev "$dev" table "$tid" >/dev/null 2>&1 || ipv4_error=1
@@ -516,25 +525,45 @@ ubus_status(){
 }
 
 start_service() {
-	local serviceStatusSummary errorStatusSummary dnsmasqStoredHash dnsmasqNewHash
+	local serviceStatusSummary errorStatusSummary dnsmasqStoredHash dnsmasqNewHash i modprobeStatus=0
 	is_enabled 'on_start' || return 1
 	if create_lock; then
 		if [ -s "$dnsmasqFile" ]; then
 			dnsmasqStoredHash="$(md5sum $dnsmasqFile | awk '{ print $1; }')"
 			rm -f "$dnsmasqFile"
 		fi
-		{ modprobe xt_set; modprobe ip_set; modprobe ip_set_hash_ip; } >/dev/null 2>&1;
 
-		ipt -t mangle -N VPR_PREROUTING; ipt -t mangle -A PREROUTING -m mark --mark "0x00/${fwMask}" -g VPR_PREROUTING;
+		for i in xt_set ip_set ip_set_hash_ip; do
+			modprobe "$i" >/dev/null 2>/dev/null || modprobeStatus=$((modprobeStatus + 1))
+		done
+
+		if [ "$modprobeStatus" -gt 0 ] && ! is_turris; then 
+ 			output "$_ERROR_: $serviceName failed to load kernel modules!\\n"
+			ubus_status 'set' "Fail: $serviceName failed to load kernel modules!"
+			return 1
+		fi
+
+		ipt -t mangle -N VPR_PREROUTING; ipt -t mangle -I PREROUTING 1 -m mark --mark "0x00/${fwMask}" -g VPR_PREROUTING;
 		if [ $forwardChainEnabled -ne 0 ]; then
-			ipt -t mangle -N VPR_FORWARD; ipt -t mangle -A FORWARD -m mark --mark "0x00/${fwMask}" -g VPR_FORWARD;
+			ipt -t mangle -N VPR_FORWARD; ipt -t mangle -I FORWARD 1 -m mark --mark "0x00/${fwMask}" -g VPR_FORWARD;
 		fi
 		if [ $inputChainEnabled -ne 0 ]; then
-			ipt -t mangle -N VPR_INPUT; ipt -t mangle -A INPUT -m mark --mark "0x00/${fwMask}" -g VPR_INPUT;
+			ipt -t mangle -N VPR_INPUT; ipt -t mangle -I INPUT 1 -m mark --mark "0x00/${fwMask}" -g VPR_INPUT;
 		fi
 		if [ $outputChainEnabled -ne 0 ]; then
-			ipt -t mangle -N VPR_OUTPUT; ipt -t mangle -A OUTPUT -m mark --mark "0x00/${fwMask}" -g VPR_OUTPUT;
+			ipt -t mangle -N VPR_OUTPUT; ipt -t mangle -I OUTPUT 1 -m mark --mark "0x00/${fwMask}" -g VPR_OUTPUT;
 		fi
+
+#		ipt -t mangle -N VPR_PREROUTING; ipt -t mangle -A PREROUTING -m mark --mark "0x00/${fwMask}" -g VPR_PREROUTING;
+#		if [ $forwardChainEnabled -ne 0 ]; then
+#			ipt -t mangle -N VPR_FORWARD; ipt -t mangle -A FORWARD -m mark --mark "0x00/${fwMask}" -g VPR_FORWARD;
+#		fi
+#		if [ $inputChainEnabled -ne 0 ]; then
+#			ipt -t mangle -N VPR_INPUT; ipt -t mangle -A INPUT -m mark --mark "0x00/${fwMask}" -g VPR_INPUT;
+#		fi
+#		if [ $outputChainEnabled -ne 0 ]; then
+#			ipt -t mangle -N VPR_OUTPUT; ipt -t mangle -A OUTPUT -m mark --mark "0x00/${fwMask}" -g VPR_OUTPUT;
+#		fi
 
 		output 1 'Processing interfaces '
 		config_load 'network'; config_foreach process_interface 'interface' 'create';
